# Generated by Django 6.1 on 2026-08-18 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found'), ('RESOLVED', 'Resolved')], default='LOST', max_length=10)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Jewelry', 'Jewelry'), ('Documents', 'Documents'), ('Clothing', 'Clothing'), ('Keys', 'Keys'), ('Accessories', 'Accessories'), ('Other', 'Other')], default='Other', max_length=50)),
                ('location', models.CharField(max_length=300)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lost & Found Item',
                'verbose_name_plural': 'Lost & Found Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
